force-app/main/default/objects/Cms_Admin_Data__c/Cms_Admin_Data__c.object-meta.xml
<CustomObject>
    <description>This object maintains the application parameters and definition for CMS</description>
    <label>Cms Admin Data</label>
    <nameField>
        <label>Admin Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cms Admin Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cms_Admin_Data__c/fields/Admin_Code_Master__c.field-meta.xml
<CustomField>
    <fullName>Admin_Code_Master__c</fullName>
    <defaultValue>(&quot;KEYN&quot;)</defaultValue>
    <description>‘KEYN’ for the parameter definition or ‘parem_sequence’ for the parameter details</description>
    <label>Admin Code Master</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cms_Admin_Data__c/fields/Admin_Code_Parent__c.field-meta.xml
<CustomField>
    <fullName>Admin_Code_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent value be used to filtering criteria for the Value</description>
    <label>Admin Code Parent</label>
    <referenceTo>Cms_Admin_Data__c</referenceTo>
    <relationshipLabel>Admin Code Children</relationshipLabel>
    <relationshipName>Admin_Code_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cms_Admin_Data__c/fields/Delete_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Delete_Indicator__c</fullName>
    <defaultValue>(&quot;N&quot;)</defaultValue>
    <description>Logical Delete Indicator(Y/N)</description>
    <label>Delete Indicator</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cms_Admin_Data__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>English
Traditional Chinese
Simplified Chinese</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language_Value_Sets</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Language_Value_Sets.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Traditional Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Simplified Chinese</fullName>
    </customValue>
    <description>Language Value Sets</description>
    <masterLabel>Language Value Sets</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AdminDataService.cls
public with sharing class AdminDataService {
  @AuraEnabled(cacheable=true)
  public static List<Cms_Admin_Data__c> getAdminDataList(
    String adminCode,
    String description
  ) {
    String filterAdminCode = '%';
    if (String.isNotEmpty(adminCode)) {
      filterAdminCode = '%' + adminCode + '%';
    }
    String filtrDescription = '%';
    if (String.isNotEmpty(description)) {
      filtrDescription = '%' + description + '%';
    }
    List<Cms_Admin_Data__c> adminCodeList = [
      SELECT
        Id,
        Name,
        Description__c,
        Language__c,
        Admin_Code_Master__c,
        Admin_Code_Parent__c,
        Delete_Indicator__c,
        CreatedById,
        LastModifiedById,
        OwnerId
      FROM Cms_Admin_Data__c
      WHERE
        (Admin_Code_Master__c = NULL
        OR Admin_Code_Master__c = 'KEYN')
        AND Name LIKE :filterAdminCode
        AND Description__c LIKE :filtrDescription
      WITH SECURITY_ENFORCED
      ORDER BY Name, Language__c
    ];
    return adminCodeList;
  }

  @AuraEnabled(cacheable=true)
  public static List<Cms_Admin_Data__c> getAdminDataChildren(
    String adminCode,
    String description
  ) {
    String filterAdminCode = '%';
    if (String.isNotEmpty(adminCode)) {
      filterAdminCode = '%' + adminCode + '%';
    }
    String filtrDescription = '%';
    if (String.isNotEmpty(description)) {
      filtrDescription = '%' + description + '%';
    }
    List<Cms_Admin_Data__c> adminCodeList = [
      SELECT
        Id,
        Name,
        Description__c,
        Language__c,
        Admin_Code_Master__c,
        Admin_Code_Parent__c,
        Delete_Indicator__c,
        CreatedById,
        LastModifiedById,
        OwnerId
      FROM Cms_Admin_Data__c
      WHERE
        Admin_Code_Master__c != NULL
        AND Admin_Code_Master__c != 'KEYN'
        AND Name LIKE :filterAdminCode
        AND Description__c LIKE :filtrDescription
      WITH SECURITY_ENFORCED
      ORDER BY Name, Language__c
    ];
    return adminCodeList;
  }
}